# config.dev.yaml
APP:
  TITLE: "Data Commerce Gateway"
  CERT: "certs/server.crt" 
  KEY: "certs/server.key" 
  IP: ""
  PORT: "8443"

DATAACCESS:
  HOST: "localhost"
  PORT: "3306"
  USERNAME: "root"
  PASSWORD: "secr3tZ"
  DBNAME: "dcgw"

LOGGER:
  LEVEL: 4
  FILENAME: "dc-gw-app.log"
  LOGPATH: "."
